import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import { RootState } from "@/state/store";
import { useDispatch, useSelector } from "react-redux";
import { useState } from "react";
import HeroSection from "@/components/HeroSection";
import { CartState } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection title="Forside" description="Lorem ipsum dolor sit amet" />
      </main>
    </>
  );
}
