import { RootState } from "@/state/store";
import axios from "axios";
import { GetServerSideProps, GetServerSidePropsResult } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";

import { WooCommerceProductList } from "@/types";
import ProductLoop from "@/components/ProductLoop";

function Shop({ products }: WooCommerceProductList) {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductLoop products={products} />
      </main>
    </>
  );
}

export default Shop;

export const getServerSideProps: GetServerSideProps = async (): Promise<GetServerSidePropsResult<{ products: WooCommerceProductList }>> => {
  const { data: products } = await axios.get(`http://localhost:4000/products/`);

  return {
    props: {
      products,
    },
  };
};
